### PR TITLE
Update react_agent.py

### PR DESCRIPTION
**Pull request by iceberg-work**
---
name: Pull Request
about: Create a pull request
---

## Description

**When I ran examples/conversation_with_react_agent/code/conversation_with_react_agent.py, I encountered the following issue:**

```
2024-03-28 23:21:58.420 | INFO     | agentscope.models:read_model_configs:171 - Load configs for model wrapper: qwen
2024-03-28 23:21:58.443 | INFO     | agentscope.utils.monitor:_create_monitor_table:341 - Init [monitor_metrics] as the monitor table
2024-03-28 23:21:58.444 | INFO     | agentscope.utils.monitor:_create_monitor_table:342 - Init [monitor_metrics_quota_exceeded] as the monitor trigger
2024-03-28 23:21:58.445 | INFO     | agentscope.utils.monitor:__init__:311 - SqliteMonitor initialization completed at [./runs\run_20240328-232156_hefdlv\agentscope.db]
2024-03-28 23:21:58.447 | INFO     | agentscope.models.model:__init__:257 - Initialize model [qwen]
2024-03-28 23:21:58.449 | INFO     | agentscope.utils.monitor:register:362 - Register metric [qwen-plus.call_counter] to SqliteMonitor with unit [times] and quota [None]
2024-03-28 23:21:58.464 | INFO     | agentscope.utils.monitor:register:362 - Register metric [qwen-plus.prompt_tokens] to SqliteMonitor with unit [token] and quota [None]
2024-03-28 23:21:58.478 | INFO     | agentscope.utils.monitor:register:362 - Register metric [qwen-plus.completion_tokens] to SqliteMonitor with unit [token] and quota [None]
2024-03-28 23:21:58.493 | INFO     | agentscope.utils.monitor:register:362 - Register metric [qwen-plus.total_tokens] to SqliteMonitor with unit [token] and quota [None]
User input: 爸爸的爸爸叫什么
User: 爸爸的爸爸叫什么
##################### ITER 1, STEP 1: REASONING ######################
assistant: {
    "thought": "\u8fd9\u662f\u4e00\u4e2a\u5173\u4e8e\u5bb6\u5ead\u5173\u7cfb\u7684\u95ee\u9898\uff0c\u4e0d\u9700\u8981\u4f7f\u7528\u5de5\u5177\u51fd\u6570\u3002",
    "speak": "\u7238\u7238\u7684\u7238\u7238\u53eb\u7237\u7237\u3002",
    "function": []
}
User input: 妈妈的妈妈叫什么
User: 妈妈的妈妈叫什么
##################### ITER 1, STEP 1: REASONING ######################
2024-03-28 23:22:38.115 | WARNING  | agentscope.models.model:checking_wrapper:182 - Fail to parsing response: {
    "text": "{{ \n    \"thought\": \"这是一个关于家庭关系的问题，不需要进行网络搜索或执行代码。\",\n    \"speak\": \"妈妈的妈妈叫外婆。\",\n    \"function\": []\n}}",
    "embedding": null,
    "image_urls": null,
    "raw": {
        "status_code": 200,
        "request_id": "e6d3f0a4-28fe-97fb-be47-92cb4b2042a6",
        "code": "",
        "message": "",
        "output": {
            "text": null,
            "finish_reason": null,
            "choices": [
                {
                    "finish_reason": "stop",
                    "message": {
                        "role": "assistant",
                        "content": "{{ \n    \"thought\": \"这是一个关于家庭关系的问题，不需要进行网络搜索或执行代码。\",\n    \"speak\": \"妈妈的妈妈叫外婆。\",\n    \"function\": []\n}}"
                    }
                }
            ]
        },
        "usage": {
            "input_tokens": 429,
            "output_tokens": 39,
            "total_tokens": 468
        }
    }
}.
 Exception: Expecting property name enclosed in double quotes: line 1 column 2 (char 1), 	 Attempt 1 / 3
2024-03-28 23:22:41.587 | WARNING  | agentscope.models.model:checking_wrapper:182 - Fail to parsing response: {
    "text": "{{ \n    \"thought\": \"这是一个关于家庭关系的问题，不需要进行网络搜索或执行代码。\",\n    \"speak\": \"妈妈的妈妈叫外婆。\",\n    \"function\": []\n}}",
    "embedding": null,
    "image_urls": null,
    "raw": {
        "status_code": 200,
        "request_id": "1f638fe8-fd8c-98bf-be4f-b186297846ad",
        "code": "",
        "message": "",
        "output": {
            "text": null,
            "finish_reason": null,
            "choices": [
                {
                    "finish_reason": "stop",
                    "message": {
                        "role": "assistant",
                        "content": "{{ \n    \"thought\": \"这是一个关于家庭关系的问题，不需要进行网络搜索或执行代码。\",\n    \"speak\": \"妈妈的妈妈叫外婆。\",\n    \"function\": []\n}}"
                    }
                }
            ]
        },
        "usage": {
            "input_tokens": 429,
            "output_tokens": 39,
            "total_tokens": 468
        }
    }
}.
 Exception: Expecting property name enclosed in double quotes: line 1 column 2 (char 1), 	 Attempt 2 / 3
2024-03-28 23:22:46.350 | WARNING  | agentscope.models.model:checking_wrapper:182 - Fail to parsing response: {
    "text": "{{ \n    \"thought\": \"这是一个关于家庭关系的问题，不需要进行网络搜索或执行其他函数。\",\n    \"speak\": \"妈妈的妈妈叫外婆。\",\n    \"function\": []\n}}",
    "embedding": null,
    "image_urls": null,
    "raw": {
        "status_code": 200,
        "request_id": "41657bb7-0cc5-9e2b-abf6-1090ac1285a3",
        "code": "",
        "message": "",
        "output": {
            "text": null,
            "finish_reason": null,
            "choices": [
                {
                    "finish_reason": "stop",
                    "message": {
                        "role": "assistant",
                        "content": "{{ \n    \"thought\": \"这是一个关于家庭关系的问题，不需要进行网络搜索或执行其他函数。\",\n    \"speak\": \"妈妈的妈妈叫外婆。\",\n    \"function\": []\n}}"
                    }
                }
            ]
        },
        "usage": {
            "input_tokens": 429,
            "output_tokens": 40,
            "total_tokens": 469
        }
    }
}.
 Exception: Expecting property name enclosed in double quotes: line 1 column 2 (char 1), 	 Attempt 3 / 3
Traceback (most recent call last):
  File "agentscope\examples\conversation_with_react_agent\code\conversation_with_react_agent.py", line 128, in <module>
    x = agent(x)
  File "agentscope\src\agentscope\agents\agent.py", line 119, in __call__
    res = self.reply(*args, **kwargs)
  File "agentscope\src\agentscope\agents\react_agent.py", line 147, in reply
    res = self.model(
  File "agentscope\src\agentscope\models\model.py", line 192, in checking_wrapper
    raise ValueError(
ValueError: fail to parsing response with: parse_func. 
  	 Attempts fails 3 times
```

**I found that sometimes LLM does not return a compliant JSON string, but instead returns a string like the following:**

{{
"thought": "xxx",
"speak": "xxx",
"function": [{{"name": "web_search", "arguments": {{"query": "what's the weather today?"}}}}]
}}

**So I modified the format expected from LLM in the string constant TOOL_HINT_PROMPT (by enclosing it with\`\`\`json and \`\`\`), and added a function extract_json_content. Here is the new return format:**

\`\`\`json
{
    "thought": "xxx",
    "speak": "xxx",
    "function": []
}
\`\`\`

**Also, sometimes LLM does not realize that it has already received an answer (even though the answer may be incorrect), so I have supplemented the string constant TOOL_HINT_PROMPT with an example of what should be returned when an answer has already been obtained.**

**The incorrect situation is as follows:**

```
2024-03-28 22:08:32.747 | INFO     | agentscope.models:read_model_configs:171 - Load configs for model wrapper: qwen
2024-03-28 22:08:32.770 | INFO     | agentscope.utils.monitor:_create_monitor_table:341 - Init [monitor_metrics] as the monitor table
2024-03-28 22:08:32.770 | INFO     | agentscope.utils.monitor:_create_monitor_table:342 - Init [monitor_metrics_quota_exceeded] as the monitor trigger
2024-03-28 22:08:32.771 | INFO     | agentscope.utils.monitor:__init__:311 - SqliteMonitor initialization completed at [./runs\run_20240328-220831_j5ai1n\agentscope.db]
2024-03-28 22:08:32.773 | INFO     | agentscope.models.model:__init__:257 - Initialize model [qwen]
2024-03-28 22:08:32.775 | INFO     | agentscope.utils.monitor:register:362 - Register metric [qwen-max.call_counter] to SqliteMonitor with unit [times] and quota [None]
2024-03-28 22:08:32.789 | INFO     | agentscope.utils.monitor:register:362 - Register metric [qwen-max.prompt_tokens] to SqliteMonitor with unit [token] and quota [None]
2024-03-28 22:08:32.803 | INFO     | agentscope.utils.monitor:register:362 - Register metric [qwen-max.completion_tokens] to SqliteMonitor with unit [token] and quota [None]
2024-03-28 22:08:32.817 | INFO     | agentscope.utils.monitor:register:362 - Register metric [qwen-max.total_tokens] to SqliteMonitor with unit [token] and quota [None]
User: 44+2
##################### ITER 1, STEP 1: REASONING ######################
assistant: {
    "thought": "Let's demonstrate how to use the execute_python_code function.",
    "speak": "I'm about to execute a simple Python script.",
    "function": [
        {
            "name": "execute_python_code",
            "arguments": {
                "code": "print('Hello from Python code!')"
            }
        }
    ]
}
####################### ITER 1, STEP 2: ACTION #######################
>>> Executing function execute_python_code ...
>>> END 
system: Execution Results:
1. execute_python_code:
    [EXECUTE STATUS]: SUCCESS
    [EXECUTE RESULT]: Hello from Python code!


##################### ITER 2, STEP 1: REASONING ######################
assistant: {
    "thought": "I am about to demonstrate how to use the execute_python_code function.",
    "speak": "I am executing a piece of Python code to calculate 44 plus 2.",
    "function": [
        {
            "name": "execute_python_code",
            "arguments": {
                "code": "print(44 + 2)"
            }
        }
    ]
}
####################### ITER 2, STEP 2: ACTION #######################
>>> Executing function execute_python_code ...
>>> END 
system: Execution Results:
1. execute_python_code:
    [EXECUTE STATUS]: SUCCESS
    [EXECUTE RESULT]: 46


##################### ITER 3, STEP 1: REASONING ######################
assistant: {
    "thought": "I am going to utilize the execute_python_code function to add 44 and 2.",
    "speak": "I will execute a Python snippet to perform the addition of 44 and 2.",
    "function": [
        {
            "name": "execute_python_code",
            "arguments": {
                "code": "print(44 + 2)"
            }
        }
    ]
}
####################### ITER 3, STEP 2: ACTION #######################
>>> Executing function execute_python_code ...
>>> END 
system: Execution Results:
1. execute_python_code:
    [EXECUTE STATUS]: SUCCESS
    [EXECUTE RESULT]: 46


##################### ITER 4, STEP 1: REASONING ######################
......
```

## Checklist

Please check the following items before code is ready to be reviewed.

- [x]  Code has passed all tests
- [x]  Docstrings have been added/updated in Google Style
- [ ]  Documentation has been updated
- [x]  Code is ready for review

### CODE REVIEW

**Comment by iceberg-work** [comment]
The following situation is possible:

```
User input: 23+567
User: 23+567
##################### ITER 1, STEP 1: REASONING ######################
assistant: {
    "thought": "The calculation is straightforward, I can do it mentally.",
    "speak": "The sum of 23 and 567 is 580.",
    "function": []
}
User input: 534*653
##################### ITER 1, STEP 1: REASONING ######################
assistant: {
    "thought": "The multiplication can be done without using a function.",
    "speak": "The product of 534 and 653 is 346,502.",
    "function": []
}
```

The calculation results are all incorrect.

**Comment by iceberg-work** [comment]
Therefore, I have modified the position of an example I added in the string constant TOOL_HINT_PROMPT, which is used to explain what should be returned when the answer has been obtained.

**Comment by DavdGao** [comment]
Thanks for your contributing. I'm curious about what's the tested model here

**Comment by DavdGao** [comment]
Thank you for your suggestion. The issue stems from two areas: 
1. the prompt engineering strategy and 
2. the JSON parsing method. 

They need to be debugged and fixed together. Therefore, we've decided to proceed with an update in #136  instead of this PR. We appreciate your contribution!

**Comment by DavdGao** [comment]
If you have any further questions or concerns, please feel free to create a new issue. Closing this for now.

**Pull request closed without merging**
